version: "3.8"
services:

  service1:
    image: lback1/epic-weapon-gen-front:v1
    build: ./service1
    container_name: service1
    deploy:
      replicas: 3
    networks:
      - example-net

  service2:
    image: lback1/epic-weapon-gen-weapons:v1
    build: ./service2
    container_name: service2
    deploy:
      replicas: 3
    networks:
      - example-net

  service3:
    image: lback1/epic-weapon-gen-rarities:v1
    build: ./service3
    container_name: service3
    deploy:
      replicas: 3
    networks:
      - example-net

  service4:
    image: lback1/epic-weapon-gen-damage:v1
    build: ./service4
    container_name: service4
    deploy:
      replicas: 3
    networks:
      - example-net

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - example-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /ect/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service1
      
networks:
  example-net: