version: "3.8"
services:
  Service1:
    image: Epic-Weapon-Generator-front:v1
    build: ./Service1
    container_name: Service-1
    networks:
      - example-net

  Service2:
    image: Epic-Weapon-Generator-weapons:v1
    build: ./Service1
    container_name: Service-1
    networks:
      - example-net

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - example-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /ect/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
networks:
  example-net: